### PR TITLE
Update the logo, form-section,footer and navbar.

### PR DESCRIPTION
**Pull request by anchalchaturvedi08**
#1187  Updated the logo, enhanced the footer and navbar and improved the form section for better usability and design. 
please add the labels too.

### CODE REVIEW

**Comment by Sampadatiwari** [comment]
@anchalchaturvedi08 share your output.

**Comment by anchalchaturvedi08** [comment]
> @anchalchaturvedi08 share your output.

Sorry, but I didn't get it.

**Comment by sampadatiwari30** [comment]
@anchalchaturvedi08 assets/css/style.css
index.html solve this conflict.

**Comment by anchalchaturvedi08** [comment]
I don't understand why my pull request was closed.

**Pull request closed without merging**
