### PR TITLE
Added Dedicated "Licensing" Page Reflecting "GPL-3.0 License"

### LINKED ISSUE #330: Add Dedicated "Licensing" Page Reflecting "GPL-3.0 License"
### Is your feature request related to a problem? Please describe.

Hey @ayush-that and @deepeshmlgupta 

The current website and repository has a license under **GPL-3.0 license** but there is no dedicated page for it. I propose to create a dedicated page that reflects the **GPL-3.0 license** in footer

image

### Describe the solution you'd like.

- The new page will include the full text of the GPL-3.0 license.
- The page will be styled consistently with the rest of the website.

1. Create a new HTML file `license.html` with the GPL-3.0 license content.
2. Apply CSS 
3. Update the footer link to point to the new `license.html` page.

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

- **Like This**

image

https://github.com/ayush-that/FinVeda/assets/101971980/353601eb-e1b6-45f2-b94e-e109840b1411

Please assign me this issue under gssoc 24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by MastanSayyad**
Hey @ayush-that and @deepeshmlgupta  | Issue Closes #330

I have added  Dedicated "Licensing" Page Reflecting "GPL-3.0 License" matching to the website design theme
 Please Take a look and review it, Thank You!!

### Screenshots

image

image

https://github.com/ayush-that/FinVeda/assets/101971980/acca68e2-d3ac-4a22-a433-d4bb651dcbae

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@MastanSayyad check your code and ensure that all check must pass successfully

**Comment by MastanSayyad** [comment]
You can Merge it @deepeshmlgupta as the checks are not related to code

**Comment by MastanSayyad** [comment]
It is github action bots greeting auto comment, you can merge it, it will work fine @deepeshmlgupta

**Comment by MastanSayyad** [comment]
@deepeshmlgupta Done

**Pull request merged**
