### PR TITLE
remove multiple footer in the help section

### PR DESCRIPTION
**Pull request by ishivansmishra**
# 👨‍💻 Description
remove multiple footer in the help section

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
)

# 📷 Screenshots/GIFs (if any)

Screenshot 2024-10-30 083856

### CODE REVIEW

**Comment by ishivansmishra** [comment]
@sampadatiwari30 Please check my PR and merge it under gssoc-ext and hacktoberfest label and give me a level

**Comment by ishivansmishra** [comment]
@sampadatiwari30 Please check and merge my PR

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by sampadatiwari30** [comment]
@ishivansmishra share your final output.

**Comment by ishivansmishra** [comment]
@sampadatiwari30 above I shared a screenshot of final output

**Review by sampadatiwari30 — APPROVED** [review]

**Pull request merged**
