### PR TITLE
Converted_Images_to_WebP_for_Better_Optimization

### PR DESCRIPTION
**Pull request by smog-root**
**Fixes** #1589 

- Converted all relevant images from formats like PNG and JPEG to WebP for better optimization and performance.
- WebP offers better compression without significant quality loss, which helps in reducing file sizes and improves page load speed.

**Changes:**

- Replaced existing image formats (JPEG, PNG) with WebP versions.
- Updated image references in HTML files to reflect the new WebP file paths.
- Verified that images render correctly in browsers that support WebP.

**Testing:**

- Verified on multiple browsers (Chrome, Firefox, etc.) to ensure proper image rendering.
- Ensured fallback mechanisms are in place for browsers that do not support WebP (if needed).

_**Note**_:  Add gssoc-ext with level3, hacktoberfest-accepted labels!

@ayush-that @sampadatiwari30

### CODE REVIEW

**Comment by smog-root** [comment]
Due it's level3 not level1. Check the issue!! @Sampadatiwari

**Comment by smog-root** [comment]
@Sampadatiwari you added level3 to the issue 😞. Now you added level1!! WHY are you doing this to me??😔

**Comment by smog-root** [comment]
I really worked hard for this!! Please add level3! @Sampadatiwari @sampadatiwari30

**Review by MastanSayyad — COMMENTED** [review]
Ideally these changes er considered as level 1 but I'll leave this as a level 3 but similar PRs like this will get level 2 @deepeshmlgupta @Sampadatiwari

**Pull request merged**
