### PR TITLE
Changed Hamburger menu

### LINKED ISSUE #670: Title: Better Hamburger Menu
### Is your feature request related to a problem? Please describe.

Currently the expanded Hamburger menu does not go well with the rest of the webpage

### Describe the solution you'd like.

Improving of the hamburger's style.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

The current style:
image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

### PR DESCRIPTION
**Pull request by VijaySamant4368**
Resolves #670 

Width of the side-nav : 70% of the device screen width (70vw)
Height of the side-nav : 100% of the device screen height (100vh)

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
Please attach the final screenshot for mobile view!

**Comment by VijaySamant4368** [comment]
Screenshot 2024-07-26 at 10-20-33 Home - FinVeda

**Comment by VijaySamant4368** [comment]
This feature has only been applied to home screen

**Comment by VijaySamant4368** [comment]
I am now doing it for other pages too.

**Comment by VijaySamant4368** [comment]
@Agarwalvidu, I had to implement the hamburger to other pages too. Should I open a new issue regarding this?

**Pull request merged**
