### PR TITLE
Added dark mode #237

### PR DESCRIPTION
**Pull request by Ayushmaanagarwal1211**
I've created dark mode for the website 
closes : #237 
please have a look 

https://github.com/ayush-that/FinVeda/assets/118350936/fbde63ee-4b10-43e8-b37b-eff61120bc92

https://github.com/ayush-that/FinVeda/assets/118350936/e07ea31c-6111-4c25-9cf8-259844629054

### CODE REVIEW

**Comment by Ayushmaanagarwal1211** [comment]
Hii @ayush-that  Can you please review it

**Comment by Ayushmaanagarwal1211** [comment]
Hii @ayush-that  please review it

**Comment by ayush-that** [comment]
image
Remove conflicts.
Also, dark mode is not implemented properly.

**Comment by Ayushmaanagarwal1211** [comment]
@ayush-that  Can you please tell me what error are you facing in dark mode implementation

**Pull request closed without merging**
