### PR TITLE
Added arrow-buttons for better viewing of testimonials

### LINKED ISSUE #727: Title: Adding of arrows to scroll the reviews
### Is your feature request related to a problem? Please describe.

Currently the only way to see some other review is to tap on the slick-dots on the bottom of the screen.

### Describe the solution you'd like.

Including of arrows can help navigate between reviews much more easier.

### Describe alternatives you've considered.

None

### Add any other context or screenshots about the feature request here.

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

### PR DESCRIPTION
**Pull request by VijaySamant4368**
Resolves #727 

For responsiveness, I divided the arrow's positions into the following parts parts:

### 1099px and less:

As there was not much space on the sides, I decided to put arrows at the bottom.

1099px:
image
500px:
image

### Between 1100px and 1199px:
On this width range, the width of the testimonials left quite much space to place the arrows at their sides:
1150px:
image

### Between 1200px and 1220px:
The width of the testimonials cards increased suddenly leaving no space for arrows in their sides:
1210px:
image

### Between 1221px and 1250px:
The width of the testimonials remains same, but the width of the screen increased, leaving a narrow place for arrows, with the same fixed width from the left and right margins.
1235 px:
image

### 1250px and more:
In this range I have made it such that it looks that the arrows are at the same distance from the left and right testimonials:
1251px:
image
1500px:
image

### CODE REVIEW

**Comment by VijaySamant4368** [comment]
Working of the arrows:

https://github.com/user-attachments/assets/4e45c633-8b21-459a-be72-16d43c4e5b8f

**Comment by VijaySamant4368** [comment]
@Agarwalvidu kindly tell me how this looks.
Thank you.

**Review by dhananjay6561 — COMMENTED** [review]
@VijaySamant4368 I was trying hard to this. This looks nice bro.

**Comment by VijaySamant4368** [comment]
> @VijaySamant4368 I was trying hard to this. This looks nice bro.

Thank you, it took me about a whole day to do it. The difficult part was making the buttons work, CSS was too much easy compared to the JS work I tried(and failed).

**Comment by dhananjay6561** [comment]
@VijaySamant4368 I can relate brother 🥲

**Comment by VijaySamant4368** [comment]
@deepeshmlgupta please add the GSSoC label and the level label.
Thank you

**Comment by VijaySamant4368** [comment]
@deepeshmlgupta @Agarwalvidu please add the GSSoC and the level label

**Comment by Agarwalvidu** [comment]
Great work!  @VijaySamant4368 
Finally it got implemented. Thank you for this.

**Comment by VijaySamant4368** [comment]
My pleasure.
@Agarwalvidu this thing can be hard to maintain so I am going to tell you in brief what I did for JS.

**Comment by VijaySamant4368** [comment]
- I first set a variable `total` equal to the number of slick dots present.
- I then got the slick with the className `slick-active`, and choosing the last element of the array returned by `getElementsByClassName(slick-active)`. Assigned its child node's id to some variable `id`.
- The IDs of the slicks are in the manner `xyz00`, `xyz01`, `xyz02` and so on.
- I extracted the last two characters, converted them to number, did addition or subtraction based on which button is pressed(remembering to loop around at less than 00 and more than the last element) and saved it to some variable 'variable', say. 
- I added 'variable',  with xyz, to get the string 'xyz##', where xyz is the first half of the string of slick-dots' ID, and ## is the value of `number` and saved the string to some variable, say, `goto-ID`.
- I got element with the id `goto-ID` with `getElementById(goto-ID)` and  saved it to the variable `targetButton`.
- Finally I used the click function, `targetButton.click()` to go to the required place.

**Comment by VijaySamant4368** [comment]
It is to be kept in mind that:
- Pressing the left arrow is equal to a person looking for the activated dot in the bottom slick-dots, and clicking on the immediate left one.
- Similarly pressing of right button is equal to pressing the dot to the right of the activated dot .
- The total count is kept by counting the number of slick-dots total.
- The ID of the first dot is like `xyz00`, therefore it would be necessary to subtract 1 from the total number of slick-dots to get the last one's ID.

**Pull request merged**
