### PR TITLE
The 3D tilt animation is added to home page

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3118 

# 👨‍💻 Description

## What does this PR do?

Sir @deepeshmlgupta , i have not changed other files this, but there was conflicts to be resolved in faq.html so i resolved them so it might show a change, else sir i have not made changes in other files.

here's the output of my PR,

https://github.com/user-attachments/assets/9499e856-eaaf-4e46-a48e-e6062ebcb570

Sir @deepeshmlgupta , please merge this PR sir.

### CODE REVIEW

**Comment by pinakviramgama** [comment]
SIr @deepeshmlgupta , i dont't know why 9 files changing is shown but sir i have not even opened those files, i don't know how this happened sir,

**Comment by pinakviramgama** [comment]
Dear @MastanSayyad , please review this PR

**Comment by deepeshmlgupta** [comment]
@pinakviramgama try to reclone it and then do the respective changes in that
then you will not get these other pages added

**Comment by deepeshmlgupta** [comment]
correct this PR also

**Pull request closed without merging**
