### PR TITLE
I have fixed the favicons issue

### PR DESCRIPTION
**Pull request by milansamuel609**
## Related Issue

Fixes:[#2046 ]
Closes:[#2046 ]

## Description

I have fixed the favicons issue in all the pages wherever there was this kind of bug.

I have done the changes in these pages :-       

	modified:   404.html
        modified:   ContactUs.html
        modified:   Finveda/Finveda/index.html
        modified:   Licensing.html
        modified:   Testimonials.html
        modified:   about.html
        modified:   auth.html
        modified:   blog.html
        modified:   blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html
        modified:   blogs/Pocketmoney.html
        modified:   blogs/Types-of-Stock-Investments-A-Quick-Guide.html
        modified:   blogs/economic-trends-and-analysis.html
        modified:   blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html
        modified:   blogs/how-fintech-is-revolutionizing-small-business-lending.html
        modified:   blogs/how-to-10x-your-generational-wealth.html
        modified:   blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
        modified:   blogs/invest-minimal.html
        modified:   blogs/privacy-policy.html
        modified:   blogs/real-estate-economics.html
        modified:   blogs/refund-policy.html
        modified:   blogs/saving-for-future.html
        modified:   blogs/senior.html
        modified:   blogs/starup.html
        modified:   blogs/terms-of-service.html
        modified:   blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
        modified:   careers.html
        modified:   contact.html
        modified:   contributors.html
        modified:   creditCard.html
        modified:   faq.html
        modified:   finance.html
        modified:   footer.html
        modified:   index.html
        modified:   login.html
        modified:   loginPage.html
        modified:   maps.html
        modified:   quiz.html
        modified:   registerpage.html
        modified:   resources/resources.html
        modified:   reviews.html
        modified:   substainability.html
        modified:   tools/contributor.html
        modified:   tools/sip.html
        modified:   tools/sip_PPF_cAL.html
        modified:   trends.html
        modified:   welcome.html

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by milansamuel609** [comment]
Please kindly check once if all the favicon issues are fixed now.

**Comment by sampadatiwari30** [comment]
@milansamuel609 share your final output.

**Comment by milansamuel609** [comment]
> @milansamuel609 finance.html solve this conflict, and share your final output.

I have resolved the conflicts please kindly check it once

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by milansamuel609** [comment]
Please kindly add the level also

**Comment by milansamuel609** [comment]
@sampadatiwari30  @ayush-that  Thank you for this opportunity to contribute.😊 I have already done a previous contribution towards the documentation also 😊

**Pull request merged**
