### PR TITLE
I have Changed the Icons on home page 

### PR DESCRIPTION
**Pull request by RitikaMaha**
Updated one:## Screenshots / videos (if applicable)
image

 
I have added necessary icons that I wanted to change. Pl do review it

### CODE REVIEW

**Comment by RitikaMaha** [comment]
I have made the necessary changes as you can see it in the home, about us, tools, etc. Now @ayush-that pl. do merge it

**Comment by deepeshmlgupta** [comment]
In nav bar the login/sign up option is not visible

**Comment by RitikaMaha** [comment]
@deepeshmlgupta I have done my task which was assigned to me. So @ayush-that I have done the needful changes assigned to me. Please do merge the request !!

**Comment by RitikaMaha** [comment]
> In nav bar the login/sign up option is not visible
@deepeshmlgupta I have done my task which was assigned to me. Why did you closed the pull request?
So @ayush-that I have done the needful changes assigned to me. Please do merge the request !!

**Pull request closed without merging**
