### PR TITLE
Hovering effect added on chat with ArthaSathi and width of the button reduced

### PR DESCRIPTION
**Pull request by Son7c**
Before

https://github.com/user-attachments/assets/8216ea9a-da08-426a-aa06-3a39f6cfe110

After

https://github.com/user-attachments/assets/9db69e84-2885-45c1-a611-ff4249c719bc

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Deekshashakyawal** [comment]
Great job !! @Son7c , Congratulations for getting your PR merged !!

**Comment by Son7c** [comment]
Thanks! Happy to contribute

**Comment by Son7c** [comment]
@Deekshashakyawal can you please add the hacktoberfest-accepted label?

**Comment by Deekshashakyawal** [comment]
Its already there

**Comment by Son7c** [comment]
> Its already there
> 

Its mentioned hacktober-accepted not hacktoberfest-accepted

**Pull request merged**
