### PR TITLE
fixed Issue No. #508

### PR DESCRIPTION
**Pull request by AnkitLuhar**
After analyzing the UI of your website, I found it to be very clean and well-designed, offering an excellent user experience. I was really impressed by your design, so I kept the navbar design simple for the mobile view ,If it doesn't look good, I can adjust the style according to your needs.

here are the ScreenShot:

**for::   min-width:768px to 991px**
Screenshot (897)
**for::   max-width 767px**
Screenshot (898)

### CODE REVIEW

**Comment by AnkitLuhar** [comment]
@Agarwalvidu kindly review the PR!

**Comment by Agarwalvidu** [comment]
Please try some other UI ideas for this, it is not much user friendly.

**Comment by AnkitLuhar** [comment]
@Agarwalvidu, do you have any suggestions for the navbar? Should it be vertical, horizontal, or have some other properties?

**Comment by Agarwalvidu** [comment]
It should be vertical only but I don't like this design!

**Comment by AnkitLuhar** [comment]
@Agarwalvidu so, should I make design like a tag , where border radius from upper is 100px and downward looks like a rectangle

**Comment by Agarwalvidu** [comment]
Umm I don't understand, please elaborate!

**Comment by Agarwalvidu** [comment]
Update?

**Comment by AnkitLuhar** [comment]
@Agarwalvidu still figuring out it ,which design will be look fine, can u suggest its helps a lot!

**Comment by AnkitLuhar** [comment]
@Agarwalvidu i think it is perfectly fine design bcz, ur website is simple so, i can't do some 3d effect or do anything with the navbar, so kindly give the suggestion as soon as possible...

**Comment by Agarwalvidu** [comment]
I am just suggesting to change the view of this, as this is not looking pleasing the shape of the Navbar that you have designed. It is more looking like a drop-down and not a Navbar!

**Comment by AnkitLuhar** [comment]
@Agarwalvidu previous navbar design for a mobile and the tablet also give a drop-down transition, if you don't like a curves at the border, so I make it rectangle in shape

**Comment by Agarwalvidu** [comment]
That was covering the whole width so it was looking more like a Navbar 
Do you have any other designs for the same?

**Pull request closed without merging**
