### PR TITLE
Welcome page Modified

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2833 

# 👨‍💻 Description

## What does this PR do?

Welcome page before :
image

Welcome page now : 

https://github.com/user-attachments/assets/35e705f9-4e8d-4c81-bbb3-d1de706c38d3

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please accept this pull request

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request

**Comment by deepeshmlgupta** [comment]
@ayush-that do review this PR

**Pull request closed without merging**
