### PR TITLE
 Fix: Add placeholder text to the name field in the feedback form.

### PR DESCRIPTION
**Pull request by salonijoshi1980**
## Description
- Fix: Add placeholder text to the name field in the feedback form
- This pull request addresses a minor usability issue in the feedback form located on the main page of the FinVeda application.

**Changes Made :**
- Added Placeholder Text: Introduced placeholder text in the name input field of the feedback form. The placeholder now prompts users with a clear indication of what information is expected (e.g., "Enter your name").

Screenshot 2024-10-27 170954

**Rationale :**
- Visual Improvement: The addition of placeholder text enhances the visual appeal of the form by providing a clearer context for users.
- Usability Enhancement: By guiding users on what to input, the placeholder text improves the overall user experience, reducing confusion and potential input errors.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

- Before solving issues : -

Screenshot 2024-10-27 150612

- After solving the issue : -

Screenshot 2024-10-27 163243

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by salonijoshi1980** [comment]
@deepeshmlgupta assign me this problem with labels of Gssoc extd , hacktoberfest and level ...Plss  i solved the issue

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by salonijoshi1980** [comment]
@sampadatiwari30 hey can u add label of hacktoberfest pls..

**Comment by salonijoshi1980** [comment]
@sampadatiwari30 can u also assign levels i need points pls! it would be great for me

**Comment by salonijoshi1980** [comment]
@sampadatiwari30 can u give me some level also , it could be great for me !

**Pull request merged**
