### PR TITLE
Add Translation Tool Done ! #1549

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #1549 

Add Translation Tool Done(All page) done ✅

Before - #1549

After -

https://github.com/user-attachments/assets/1edca2bb-00e1-4393-9662-6e43b794d215

Screenshot 2024-10-19 232547
Screenshot 2024-10-19 232556
Screenshot 2024-10-19 232611
Screenshot 2024-10-19 232621
Screenshot 2024-10-19 232634
Screenshot 2024-10-19 232643
Screenshot 2024-10-19 232652
Screenshot 2024-10-19 232705
Screenshot 2024-10-19 232714

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________
## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@Subhajit-2023-44 solve the conflicts of faq.html

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 solve the conflicts of faq.html

@deepeshmlgupta Conflicts ? sorry I didn't find any conflicts..

Earlier also a pull request you asked to resolve the conflicts and close my PR but there was no conflicts either. 
Later you said this -
Screenshot 2024-10-20 010432

@deepeshmlgupta  PA please check again maybe there is a technical issue..

Thank you

**Comment by deepeshmlgupta** [comment]
> > @Subhajit-2023-44 solve the conflicts of faq.html
> 
> @deepeshmlgupta Conflicts ? sorry I didn't find any conflicts..
> 
> Earlier also a pull request you asked to resolve the conflicts and close my PR but there was no conflicts either. Later you said this - Screenshot 2024-10-20 010432
> 
> @deepeshmlgupta PA please check again maybe there is a technical issue..
> 
> Thank you


Done

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta sir kindly upgrade the level 2 to 3, Because I have added translation tools to all pages(7 pages)

Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta Thank you sir  🙏🏻

**Comment by deepeshmlgupta** [comment]
> @deepeshmlgupta Thank you sir  🙏🏻

Your welcome 🤗

**Pull request merged**
