### PR TITLE
The Toggle of FAQs IS Done with JS

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2798 

# 👨‍💻 Description

## What does this PR do?

The toggling of questions of faqs was not going to done but it is modified with the help of js

here's the detailed output video , please check it out.

https://github.com/user-attachments/assets/ff9ae47c-66f6-4c0b-943e-c93cb4f72320

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , i have resolved issue number #2798 , please review this pull request.

**Comment by sampadatiwari30** [comment]
@pinakviramgama blog.html solve this conflict.

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request as conflicts are resolved.

**Comment by deepeshmlgupta** [comment]
@ayush-that review this PR

**Comment by ayush-that** [comment]
@pinakviramgama The present implementation is better in terms of UI and UX. Hence I'm closing this PR. I appreciate your time.

{D3824B0F-FA78-4E6A-A69B-4EA8CCBFA6C1}

**Comment by pinakviramgama** [comment]
But sir toggle is not seen in question off in that form, so i made this PR @ayush-that

**Pull request closed without merging**
