### PR TITLE
Add Translation Tool done ! #1236

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Fixed issue - #1236
Add new feature - Translation Tool

https://github.com/user-attachments/assets/fb8363a0-a114-4bc1-bdd3-3cc962215855

## Description
[I add new feature - Translation Tool]

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Hemu21** [comment]
@sampadatiwari30   I am one of the program managers of gssoc-ext. can you please change the level. It is the favicon update. So level 2 is needed not level 3. I hope you understand. Can you please update the label

**Comment by Subhajit-2023-44** [comment]
> @sampadatiwari30 I am one of the program managers of gssoc-ext. can you please change the level. It is the favicon update. So level 2 is needed not level 3. I hope you understand. Can you please update the label

@Hemu21 Sir🙏🏻 please don't get me wrong but if you check other contributors who have added translation tool to any project they all got level 3 for it..

Sir can you please give me level 3 for this? I would be very grateful if you could give me level 3 for this..

Thank You 🙏🏻

**Comment by Hemu21** [comment]
> > @sampadatiwari30 I am one of the program managers of gssoc-ext. can you please change the level. It is the favicon update. So level 2 is needed not level 3. I hope you understand. Can you please update the label
> 
> @Hemu21 Sir🙏🏻 please don't get me wrong but if you check other contributors who have added translation tool to any project they all got level 3 for it..
> 
> Sir can you please give me level 3 for this? I would be very grateful if you could give me level 3 for this..
> 
> Thank You 🙏🏻

I saw your prs are good. You have got many level3 in different repos for this. Our team is reviewing top 100 contributors prs. I mentioned in this one pr of your related to translate as level2. I doesn't mentioned your relevant prs like this. So I hope you understand.

**Comment by Subhajit-2023-44** [comment]
> > > @sampadatiwari30 I am one of the program managers of gssoc-ext. can you please change the level. It is the favicon update. So level 2 is needed not level 3. I hope you understand. Can you please update the label
> > 
> > 
> > @Hemu21 Sir🙏🏻 please don't get me wrong but if you check other contributors who have added translation tool to any project they all got level 3 for it..
> > Sir can you please give me level 3 for this? I would be very grateful if you could give me level 3 for this..
> > Thank You 🙏🏻
> 
> I saw your prs are good. You have got many level3 in different repos for this. Our team is reviewing top 100 contributors prs. I mentioned in this one pr of your related to translate as level2. I doesn't mentioned your relevant prs like this. So I hope you understand.

Okay sir, Thank You 🙏🏻

**Pull request merged**
