### PR TITLE
Favicon-Icon added in profile.html

### PR DESCRIPTION
**Pull request by pinakviramgama**
Fixes issue number #2662 

Dear @Sampadatiwari , i have added favicon icon in profile.html page.

please approve my code.
image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , i have added favicon icon in profile.html page, please merge this pull request. And approve my code

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @ayush-that , please merge this pull request as i  have resolve issue number #2662

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request as issue number #2662  is been resolved

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please approve this pull req.

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari please approve this pull request

**Comment by sampadatiwari30** [comment]
@pinakviramgama no need. check the website again.

**Pull request closed without merging**
