### PR TITLE
update in Blog card Background color

### PR DESCRIPTION
**Pull request by Sujal942**
## Related Issue
Change in background linear gradient color.

## Description
Choose appropriate color for Blog Card so look good and match the theme of website.

## Type of PR
- [style]: Change color of blog cards #1275

## Screenshots / videos (if applicable)
https://github.com/user-attachments/assets/1ba51871-d5b6-44d7-ab82-c1707509e8ef

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@Sujal942 assets/css/style.css solve this conflict.

**Comment by Sujal942** [comment]
@sampadatiwari30 changes are done, please take a look!

**Comment by sampadatiwari30** [comment]
@Sujal942 it's not too good, you can do it more better.

**Comment by Sujal942** [comment]
@sampadatiwari30  Okay, I change the background again. If there is a change in the backdrop color, please notify me and give me with the details of the modification so that I can update their color.

**Comment by sampadatiwari30** [comment]
@Sujal942 now it's better.  then assets/css/style.css solve this conflict.

**Comment by Sujal942** [comment]
@sampadatiwari30 changes are done, please take a look again!

**Pull request merged**
