### PR TITLE
Pie chart generator added

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3053 

# 👨‍💻 Description

## What does this PR do?

Added new feature named pie chart generator which generates pie chart on basis of input from user of their savings, investments and expenses.

here's the output of it.

https://github.com/user-attachments/assets/4d8c2b93-a73c-4cbb-8b08-7ddb1cf2b101

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@pinakviramgama 
can you explain me what are you changing in Testimonials.html, new.html, demo.html, addBlog.html, blog.html

**Comment by pinakviramgama** [comment]
Dear Sir, @deepeshmlgupta i have not made changes in other files, just made changes in index.html and created piechart file,

as i am working on another issue of testimonials.html as that file is not opening and only buffering so it might shown that there are changes.

**Comment by deepeshmlgupta** [comment]
So, its better to check you commit before pushing it in your PR so that it should be clear.
As you are working on other issues them add these files there and but in this pr only add the file that are related to this pr only

**Comment by pinakviramgama** [comment]
Sorry sir  @deepeshmlgupta  for that  mistake, i will try not to repeat that,

sir, i have updated the commit, please merge this PR.

**Comment by pinakviramgama** [comment]
Sir @deepeshmlgupta , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR

**Comment by deepeshmlgupta** [comment]
@pinakviramgama firstly you have to remove the unnecessary files that are not need for modification for this PR then only this PR will merge

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , sir i tried my best to make previous changes revert , but sir i have not made any changes in other files and sir previous changes are not able to fetch, sorry sir for that.

please sir guide me now what should i do.

**Comment by pinakviramgama** [comment]
sir @deepeshmlgupta , it could be due to the single blank spaces that i by mistake have pressed in other files so changes might have reflected but sir i have not made any other changes any other files

**Comment by pinakviramgama** [comment]
Sir @deepeshmlgupta , if you permit then can i delete those files which are not necessary so that if you merge this PR so that file changes won''t  get reflected

**Comment by pinakviramgama** [comment]
Sir @deepeshmlgupta , please guide me sir what should i do now, please sir guide me.

**Comment by pinakviramgama** [comment]
Dear @MastanSayyad , please review this PR.

**Comment by deepeshmlgupta** [comment]
you can delete those files that are not need so that it can easy for me to review this

**Pull request closed without merging**
