### PR TITLE
Blogs are able to add with help of JAVASCRIPT

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2903 

# 👨‍💻 Description

## What does this PR do?

The blogs were not able to add before as button was not working functionally

now new features are added so blogs are posted and here's some features of it.
1) Blogs can be shared on Instagram, Linkedin or twitter
2) blogs can have images
3) blogs can be deleted anytime

https://github.com/user-attachments/assets/9a58be95-7bc2-40b6-9e6d-6deee42e6242

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , i have uploaded video of the output, please ensure the functionalities and please merge this pull request.

**Comment by sampadatiwari30** [comment]
@pinakviramgama blog.html solve this conflict.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , please merge this pull request as conflict is resolved.

**Comment by deepeshmlgupta** [comment]
@ayush-that review this PR

**Comment by pinakviramgama** [comment]
This PR Also solves issue #2961

**Comment by ayush-that** [comment]
@pinakviramgama Honestly, I do not get the point of this. What feature is this adding? The "blog" you're publishing does not save anywhere & the share buttons are useless.

{AC2A8B60-0E19-409C-8357-FFA57ED419A0}

For that reason I'm closing this PR. Appreciate your efforts.

**Pull request closed without merging**
