### PR TITLE
Blogs page working functionalyy

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2770 

# 👨‍💻 Description

Blogs page was not working as we add blog or delete

Now blog page is modified using JavaScript that it is workign functionalyy

here's the output as folllows

image

image

image

deleting blogs allso modified

blog deleted
image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , will i get points of this as none of the lablels were assigned to this pull request?

**Comment by deepeshmlgupta** [comment]
> ### his branch was successfully deployed
> 1 active deployment

added labels

**Comment by deepeshmlgupta** [comment]
> Dear @deepeshmlgupta , will i get points of this as none of the lablels were assigned to this pull request?

added labels

**Pull request merged**
