### PR TITLE
Add profile icon in all page done ! 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add profile icon in all page done -

https://github.com/user-attachments/assets/e8e1a016-c05a-4066-b153-963112c1ca2b

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta sir can you please give me level 3 for this because I added profile icon in all page.. you can check my code i added a lot..

I would be very grateful if you could give me level 3 for this.. Thank You 🙏🏻

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
solve the conflicts of blog.html

**Comment by Subhajit-2023-44** [comment]
> solve the conflicts of blog.html

@deepeshmlgupta sir done

**Comment by Subhajit-2023-44** [comment]
Thank You sir

**Pull request merged**
