### PR TITLE
Added email Validation to accept approved domains

### PR DESCRIPTION
**Pull request by Amruta7203**
This improvement ensures that only email addresses with specific domain extensions (e.g., ".com", ".in") are considered valid. It adds an additional layer of validation by checking if the domain part of the email address belongs to a pre-defined list of approved domains.
image
image
image

### CODE REVIEW

**Comment by ayush-that** [comment]
image

Please always mention what issue you are solving with the PR.
Remove this green colour on hover, please.

**Comment by Amruta7203** [comment]
@ayush-that This PR resolves the problem you mentioned above. Moreover, it accepts emails of verified domains only.

**Comment by Amruta7203** [comment]
@ayush-that Request you to reopen this PR and review it again

**Comment by ayush-that** [comment]
> Remove this green colour on hover, please.

Remove this green colour on hover, please.
I'll merge it then.

**Pull request closed without merging**
