### PR TITLE
Implemented sliding animation for mobile navbar and fixed the hamburger icon click functionality.

### PR DESCRIPTION
**Pull request by PrityanshuSingh**
### Related Issue:
Mobile Navbar Slide-In Not Triggering on Hamburger Icon Click

### Description:
This pull request addresses the issue where the hamburger icon in mobile view is not triggering the navbar to slide open. As a result, users are unable to access the navigation links effectively. This fix implements a smooth sliding animation for the mobile navbar when the hamburger icon is clicked, ensuring the navbar slides in from the side and is fully responsive.

### Type of PR:
- [X] Feature enhancement : #1347

### Screenshots / Videos (if applicable):

https://github.com/user-attachments/assets/1f0d7a9c-4ad7-4544-906d-9255bf945b80

### Checklist:
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### Additional Context:
These changes improve the user experience in mobile view by ensuring the navbar becomes accessible through a smooth slide-in animation. This update is consistent across different mobile browsers and enhances the overall navigation experience. An optional slight overlay and close button inside the navbar were also considered for further usability improvements.

### Urgency (Optional):
High priority. The issue directly affects mobile navigation, making it crucial to the website's functionality on smaller screens.

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@PrityanshuSingh solve all the conflicts, and share output.

**Comment by PrityanshuSingh** [comment]
Hi @sampadatiwari30,

The conflicts have been successfully resolved. The video demonstration of the mobile Navbar functionality is included in the PR.

Thank you!

**Review by deepeshmlgupta — APPROVED** [review]
@PrityanshuSingh solve the conflicts rest all is fine

**Comment by Sampadatiwari** [comment]
@PrityanshuSingh index.html solve this conflict.

**Comment by PrityanshuSingh** [comment]
@deepeshmlgupta @Sampadatiwari , thanks for the review, i have resolved the conflicts. 

image

**Pull request merged**
