### PR TITLE
fixed tool page

### PR DESCRIPTION
**Pull request by Ketanop321**
#464

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
It still has merge conflicts @Ketanop321

**Comment by Ketanop321** [comment]
> It still has merge conflicts @Ketanop321

sorry for the creating conflict issue but i am not able to find the cause of  conflict , in my local machine is is working perfectly, can you please tell me briefly how can i solve this conflicttt...😭😭🙏

**Comment by Agarwalvidu** [comment]
Actually Tools page is updated, so you have to sync your fork with the updated fork, then you have to fetch the changes then only you will be able to resolve the the conflicts.

**Comment by Agarwalvidu** [comment]
Please try to solve these conflicts using the above told method. @Ketanop321

**Pull request closed without merging**
