### PR TITLE
Add a User Profiles page done ! #2562

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature -  #2562
Add a normal user profile page and a profile icon in the home page navbar that redirects to the profile page done -

https://github.com/user-attachments/assets/b137fa39-0bfc-4501-839d-a250380fab33

Screenshot 2024-11-01 175149

Screenshot 2024-11-01 175204

Screenshot 2024-11-01 175213

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am please give me Level 3, you can check my code..

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am please give me Level 3, you can check my code...

Screenshot 2024-11-01 212143

Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am kindly upgrade the Level 2 to 3, you can check my code...

Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am 🙏🏻 kindly upgrade the Level 2 to 3, you can check my code, please check I have added a lot...

Thank You

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am 🙏🏻 kindly upgrade the Level 2 to 3, check my code I have added a lot...

Thank You

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am please add level 3 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ma'am thanks a lot 🙏🏻🥹

**Pull request merged**
