### PR TITLE
Toggle is Done Using JavaScript

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2798 

# 👨‍💻 Description

## What does this PR do?

BEFORE : The toggle button in FAQ section was not working at all

image

NOW : Modified using javaScript and css changes

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , toggle button is working now, please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please accept this pull request

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please approve my code

**Comment by pinakviramgama** [comment]
Dear sir @Sampadatiwari , my 5 pull request are only pending since tomorrow, if there's any kind of error or issue, please assist me so i will do it, please accept my request as only my pull requests are been not accepted since one day.

**Comment by deepeshmlgupta** [comment]
@ayush-that kindly review this PR

**Pull request closed without merging**
