### PR TITLE
Pie - chart generator added

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3053

# 👨‍💻 Description

## What does this PR do?

https://github.com/user-attachments/assets/8ecf0360-8eeb-496b-ac4d-19c8ed946d5a

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR.

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR.

**Comment by pinakviramgama** [comment]
dear @Sampadatiwari , please merge this pr

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , @deepeshmlgupta , please merge this PR.

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
Good Work @pinakviramgama that the work I am expecting from well done

**Pull request merged**
