### PR TITLE
The Toggle working for FAQ without UI changes

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2798 

# 👨‍💻 Description

## What does this PR do?

Dear Sir @deepeshmlgupta , i have not made UI changes and worked on same ui and toggle button is working.

here's the output, please merge this request if you liked my contribution, if there are changes to be made, please assist me.

https://github.com/user-attachments/assets/bd91fe74-f8b8-4a8d-8916-fc012c059782

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@pinakviramgama can you explain what is the need of demo.html
also share me a video of what is this demo.html is working and also share the video of your demonstration

**Comment by pinakviramgama** [comment]
Sir firstly i am trying to make changes which i wanna do in demo.html, then final changes i am printing in main file 
for eg : faq.html, so to avoid mistake and other unnecessary changes i try demo.html first.

**Comment by pinakviramgama** [comment]
Dear  Sir @deepeshmlgupta here's the output of demo.html

Uploading 127.0.0.1_5500_FinVeda_demo.html and 1 more page - Personal - Microsoft​ Edge 2024-11-08 17-52-24.mp4…

**Comment by deepeshmlgupta** [comment]
> Dear Sir @deepeshmlgupta here's the output of demo.html
> 
> Uploading 127.0.0.1_5500_FinVeda_demo.html and 1 more page - Personal - Microsoft​ Edge 2024-11-08 17-52-24.mp4…

reupload its not uploaded

**Comment by pinakviramgama** [comment]
Sir @deepeshmlgupta  next time i will not create demo.html, sorry for that inconvenience

**Comment by pinakviramgama** [comment]
https://github.com/user-attachments/assets/47c6a332-7d75-4451-8af0-14645aefb02c

demo.html

**Comment by pinakviramgama** [comment]
Sir @deepeshmlgupta , uploaded demo.html

**Comment by deepeshmlgupta** [comment]
it's better that you remove demo.html if it is of no use as this demo.html will also added in our code base if I merge your PR

**Comment by pinakviramgama** [comment]
ok sir, i am updating commit in this PR.
and sorry sir for this mistake @deepeshmlgupta

**Comment by deepeshmlgupta** [comment]
> ok sir, i am updating commit in this PR. and sorry sir for this mistake @deepeshmlgupta

it's ok 
also if the demo.html is of no use in this #3013  pr also then remove it form there also

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , i have deleted demo.html, please merge this PR.

**Comment by deepeshmlgupta** [comment]
I think new.js is also not in use

**Review by deepeshmlgupta — APPROVED** [review]

**Pull request merged**
