### PR TITLE
Remove Add/Your Feature text below the login button to reduce user confusion and improve clarity regarding the login and registration functionalities.

### PR DESCRIPTION
**Pull request by salonijoshi1980**
## Description
- Fix: Remove Add/Your Feature text below the login button.
- This pull request addresses a minor usability issue on the Login/Register page. By removing the "Add/Your Feature" text, we aim to reduce user confusion and improve clarity regarding the login and registration functionalities. This change enhances the user experience by making the purpose of the buttons more straightforward.

**Changes Made :**
- Removed Text: "Add/Your Feature" below the login button.
- Impact: This change helps clarify the login/register functionality, reducing potential confusion for users.

Screenshot 2024-10-28 131210

**Rationale :**
- Clarity Improvement: Removing the "Add/Your Feature" text enhances the clarity of the Login/Register page by eliminating unnecessary information that may confuse users.
- Usability Enhancement: This change streamlines the user interface, making it easier for users to understand the primary actions they need to take, ultimately improving the overall user experience.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

- Before solving issues : -

Screenshot 2024-10-28 112212

- After solving the issue : -

Screenshot 2024-10-28 131350

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by salonijoshi1980** [comment]
@Sampadatiwari , @ayush-that assign this to me pls.. with labels of Gssoc extd , hacktoberfest with levels✨😊

**Comment by salonijoshi1980** [comment]
there is a small conflict occur of closed div tag are not indent with open div so just clear it  and all things are done!

**Comment by deepeshmlgupta** [comment]
@salonijoshi1980 sovle the conflicts in loginPage.html

**Comment by salonijoshi1980** [comment]
@deepeshmlgupta , @sampadatiwari30 , @ayush-that assigned me Pls.. with this problem of label Gssoc extd , hacktoberfest and level 2 , i need points if u assigned with this it would be great!✨

**Comment by salonijoshi1980** [comment]
@deepeshmlgupta hey pls... give me the label of level i need points.

**Pull request merged**
