### PR TITLE
ADD MORE CARDS AND CAROUSEL EFFECT IN "ABOUUT US SECTION" IN ABOUT PAGE #2189

### PR DESCRIPTION
**Pull request by isimarjitsingh**
Fixes:  #(#2189)

# Description

so basically i just MANIPULATE the  Recommended Books on Finance" IN CARRERS PAGE   which gives the interactive interface for going  smoothly. This page deals with to collecting reviews from users regarding your website.  Transitions ,keyframes are used in these making it more interactive and the the things are unable to show in one picture just go and check  out  the transitions for hovering effects if you like the designing then  please rate it as "level3" or "level 2" label 👍 .

AS I ADDED:-
-  USED JS FOR CAROUSEL EFFECT
- MAKE A CAROUSEL
- ADD NEW CARDS
- -FIND PHOTOS
- MAKE CARDS BY OWN
- ADD HOVER EFFECTS

#  ADD MORE CARDS AND CAROUSEL EFFECT IN "ABOUUT US SECTION" IN ABOUT PAGE #2189

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

# Screenshots / videos (if applicable)

--BEFORE:-
Screenshot 2024-10-27 140908

---AFTER:-
Screenshot 2024-10-27 213429
Screenshot 2024-10-27 215114

# Checklist:

- [x] I have made this change from my own.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers and screenshots after making the changes.

### CODE REVIEW

**Comment by isimarjitsingh** [comment]
@Sampadatiwari  @deepeshmlgupta  KINDLY GIVE IT A LEVEL 3 "IF POSSIBLE" AS I TOTTALY CHANGED THE DESIGNING OF FORM WHICH SUPPORTS YOUR WEBSITE THEME AND LET ME KNOW IF THERE IS ANY ISSUE.

AND KINDLY PROVIDE GSSOC EXTD.

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
Solve the conflicts @isimarjitsingh in about.html

**Comment by isimarjitsingh** [comment]
OK

**Comment by isimarjitsingh** [comment]
conflicts are solved

**Review by deepeshmlgupta — APPROVED** [review]

**Pull request merged**
