### PR TITLE
Enhancement: Make about.html responsive for small and extra-small screens.

### PR DESCRIPTION
**Pull request by salonijoshi1980**
## Description
- Enhancement: Make about.html responsive for small and extra-small screens.
- This pull request addresses the need for improved responsiveness on the about.html page, ensuring that users have a better experience on mobile devices. By enhancing the layout for small and extra-small screens, we aim to provide a more accessible and user-friendly interface.

**Changes Made :**
- Improved Responsiveness: Adjusted layout and styling of the about.html page for better viewing on mobile devices.
- Impact: This change helps users navigate and read content more easily on smaller screens, improving overall usability.

Screenshot 2024-10-29 203855

Screenshot 2024-10-29 203909

**Rationale :**
- Improved Readability: Ensures that text and images adjust to fit smaller screens, making content easier to read on mobile devices.
- Better Navigation: Adjusted layout improves navigation and usability on smaller screens, allowing users to access information quickly without excessive scrolling or zooming.
- Enhanced Accessibility: Accommodates users who primarily use mobile devices, improving accessibility for a broader audience.
- Faster Load Times: Responsive elements load faster on mobile, improving performance and reducing wait times.
- Consistent User Experience: Delivers a uniform experience across devices, allowing users to switch between devices seamlessly.

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

- Before solving issues : -

Screenshot 2024-10-29 193038

- After solving the issue : -

Screenshot 2024-10-29 193927

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:

- This Enhancement would enhance the vision of whole about.html page  and it cannot create the confusion like before!

### CODE REVIEW

**Comment by salonijoshi1980** [comment]
@deepeshmlgupta , @sampadatiwari30  Assign me with this pls.. with the **( level 3)** label and **hacktoberfest** , **gssoc extd **label, in previous  pull request u cannot assigned me with **level** label but this time i need it  ,it would be great if u do this!🦋Pls..

**Comment by sampadatiwari30** [comment]
@salonijoshi1980 resolved.

**Comment by salonijoshi1980** [comment]
@sampadatiwari30 ..why it's unmerged?

**Comment by Sampadatiwari** [comment]
@salonijoshi1980 okay you can do it

**Comment by salonijoshi1980** [comment]
assigned this also @sampadatiwari30 give a level 1 it would be great

**Pull request closed without merging**
