### PR TITLE
Added NAVBAR in FINANCIAL GOAL TRACKER page

### PR DESCRIPTION
**Pull request by neeru24**
# 🛠️ Fixes Issue
Fixes: #3136

# 👨‍💻 Description

## What does this PR do?

Added NAVBAR in FINANCIAL GOAL TRACKER page

## Before: 
image

## After: 
image

#### KINDLY MERGE IT WITH LEVEL 3 if possible

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@neeru24 the login button is not properly placed

**Comment by neeru24** [comment]
> @neeru24 the login button is not properly placed also added the same style nab bar as of other pages. as in this nab bar the search box is missing and logo is also different

@deepeshmlgupta 
Done:
image

**Comment by deepeshmlgupta** [comment]
share a video of your work

**Comment by neeru24** [comment]
> share a video of your work

Ok

**Comment by neeru24** [comment]
> share a video of your work
 
I'm not able to upload video from laptop screen recording
image

**Comment by deepeshmlgupta** [comment]
search bar is missing

**Comment by neeru24** [comment]
> search bar is missing

I made the navbar like these pages. They have no search bar.... so kindly merge it 

image

image

**Review by deepeshmlgupta — APPROVED** [review]

**Pull request merged**
