### PR TITLE
update footer properly according to screen width

### PR DESCRIPTION
**Pull request by dipak2005**
# 🛠️ Fixes Issue
Fixes: #2726 
closes: #2726 
# 👨‍💻 Description

 fixing footer issue and set the footer according to screen width 

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots / videos : 
before changes : 

https://github.com/user-attachments/assets/359c2c70-6df4-4df9-a998-16b5f0db3b48

after changes : 
 
https://github.com/user-attachments/assets/83c86914-5ec2-4f30-b366-6cae23c99857

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by dipak2005** [comment]
@deepeshmlgupta , @sampadatiwari30 plz accept my pr

**Comment by sampadatiwari30** [comment]
@dipak2005 index.html solve this conflict.

**Comment by dipak2005** [comment]
> @dipak2005 index.html solve this conflict.

i resolve index.html merge conflict plz consider my pr

**Comment by sampadatiwari30** [comment]
@dipak2005 finance.html solve this conflict.

**Comment by dipak2005** [comment]
@sampadatiwari30 i resolve the conflict plz accept my pr

**Review by deepeshmlgupta — APPROVED** [review]

**Pull request merged**
