### PR TITLE
Fix Overflow Issue in Contributor Card

### PR DESCRIPTION
**Pull request by IkkiOcean**
Closes : #2731 

# 👨‍💻 Description

This PR addresses the issue where the content within each contributor card was overflowing beyond the card boundaries. To improve the layout and ensure that all content stays within the card, I applied several CSS adjustments to constrain the elements and prevent overflow. This update enhances the visual appearance and consistency of the contributor cards.

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/901ead5b-3d2c-4751-9e3b-af584b3ea686

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@IkkiOcean resolved.

**Comment by IkkiOcean** [comment]
@sampadatiwari30 hey why didnt you merge it? I was assigned with the issue.

**Comment by sampadatiwari30** [comment]
@IkkiOcean before you, assigned to another contributor.

**Comment by IkkiOcean** [comment]
> @IkkiOcean before you, assigned to another contributor.

Can you please merge and just revert. Since I did work on it?

**Pull request closed without merging**
