### PR TITLE
Add FinVeda icon on navbar of all pages

### PR DESCRIPTION
**Pull request by Sudhanshu248**
## Related Issue
Add Icon Of FinVeda on Navbar #1364 

## Description
There is no icon of FinVeda on navbar on all pages. Without icon website not looks good.

I've added icon on navbar and also fixed the bugs of navbar.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement

## Screenshots / videos (if applicable)
Before:
Screenshot 2024-10-17 172805

After:
Screenshot 2024-10-17 172834

## Checklist:
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@Sudhanshu248 please make it more better.

**Comment by Sudhanshu248** [comment]
@sampadatiwari30 Mam can you give me the icon which looks good on navbar so that I can add it.

**Comment by sampadatiwari30** [comment]
@Sudhanshu248 you can use any tool, which gives you idea.

**Comment by sampadatiwari30** [comment]
@Sudhanshu248 about.html
assets/css/style.css solve this conflict.

**Comment by Sudhanshu248** [comment]
@sampadatiwari30 Kindly review my pr I've soled the conflict problem.  "Please let me know if there's anything I can do."

**Comment by Sudhanshu248** [comment]
@sampadatiwari30 Mam Can you give the design of the logo. Which type of design logo do you want. So that I will create that and add in the navbar.

**Pull request merged**
