### PR TITLE
added the nav bar active feature

### LINKED ISSUE #103: UI Improvements
Improving ui by providing underline in the navbar section of the page currently visited
Before
image
After
image
my drawing is bad!

### PR DESCRIPTION
**Pull request by YadlaMani**
closes #103

### CODE REVIEW

**Comment by ayush-that** [comment]
image
Fix this bug.

**Comment by YadlaMani** [comment]
@ayush-that it's not a bug this shows current active page i feature is suggested

**Comment by ayush-that** [comment]
> @ayush-that it's not a bug this shows current active page i feature is suggested

image
Only works on home page.

**Comment by YadlaMani** [comment]
i am fixing that issue it will work for all pages will do that keep the pull request again

**Pull request closed without merging**
