### PR TITLE
Refactor Navbar Style ✨

### PR DESCRIPTION
**Pull request by AnushkaChouhan25**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state “None”] #2089 

## Description
Grouped less frequently used pages under a "Explore" dropdown and Keep only the most important or frequently accessed links visible on the main navbar for a streamlined appearance.

## Type of PR

- [x] Feature enhancement
- [ ] Documentation update 

## Screenshots / videos (if applicable)
image
image

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
Implement this nav bar on other pages of the website also ...

**Comment by AnushkaChouhan25** [comment]
Okay Sure @deepeshmlgupta

**Comment by deepeshmlgupta** [comment]
@AnushkaChouhan25 just leave a comment when its done

**Comment by AnushkaChouhan25** [comment]
Done @deepeshmlgupta

**Pull request merged**
