### PR TITLE
Working Testimonials Page

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3054 

# 👨‍💻 Description

## What does this PR do?

The testimonials page was constantly buffering only and not showing any kind of output, but now it's been modified acording to user interactions

here's the output of it :

BEFORE :

https://github.com/user-attachments/assets/7429b4de-2e12-4869-87e8-870a313bcbdf

NOW :

https://github.com/user-attachments/assets/8a63d7bf-0601-464e-a90c-d2bb5f6cf601

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please merge this PR

**Comment by deepeshmlgupta** [comment]
@pinakviramgama firstly you have to remove the unnecessary files that are not needed for modification for this PR then only this PR will merge

**Comment by deepeshmlgupta** [comment]
If you can delete those files that are note used in your this PR then open this PR again 
I am closing this PR

**Pull request closed without merging**
