### PR TITLE
#1502 Issue (Solved):- Added pop up

### PR DESCRIPTION
**Pull request by PrAyAg9**
## Description
Registration pop up here you can mention the top deal/offers currently website has to offer i have built a format and design of it and added Js which works you can keep changing text and deals according to you. This deals will make customers to stick towards the website.

Solves - #1502 

## Type of PR

- [ ] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X ] I have performed a self-review of my code
- [ X] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [ X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by PrAyAg9** [comment]
image

Is this design good ?

**Comment by sampadatiwari30** [comment]
@PrAyAg9 it's not good, you can design an interactive page.

**Comment by PrAyAg9** [comment]
> @PrAyAg9 it's not good, you can design an interactive page.

@sampadatiwari30  Well pop up is the one which comes at landing page, you didn't like both the UI of registration pop , actually it will just come when user opens it unregistered on site and he can close it in seconds, so that's how it will work. I didn't understand what are you trying to say?

**Comment by Sampadatiwari** [comment]
@PrAyAg9 I know very well, I'm saying that, change the image of pop up. And make it interactive.

**Comment by PrAyAg9** [comment]
@Sampadatiwari  Thank you for clearance, what type of image should i put there firstly i was trying to match the background see i used two designs tell me which one is better atleast?

**Comment by sampadatiwari30** [comment]
@PrAyAg9 first one is little bit better.

**Comment by deepeshmlgupta** [comment]
@PrAyAg9 can you share the final design that you have created and updated to your PR as well

**Pull request closed without merging**
