### PR TITLE
 UI improvement of BLOG Page

### PR DESCRIPTION
**Pull request by isimarjitsingh**
## Description
basically i changed the designing of BLOG  section to build a smooth user interface:-
- GIVE  a different box for content 
- easy to read and eye catching effects for content
- i add transitions for smooth hovering
- button color changed
- give a eye catching colours
- give a relevant Image 
- there are so many another things which unable to tell in documentation ,so  you need to cheque it out .
- now you also able to read content

## Type of PR

- [ ] Bug fix
- [ x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
BEFORE:-
Screenshot 2024-10-17 151051

AFTER:-
Screenshot 2024-10-17 131943

## Checklist:
- [X ] I have read and followed the Contribution Guidelines.
- [X ] I have tested the changes thoroughly before submitting this pull request.
- [X ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Kindly merge it and if there is any issue, kindly let me know!!

#1387

### CODE REVIEW

**Comment by Sampadatiwari** [comment]
@isimarjitsingh you can redesign the "Blog post" and make it better, it's not too good.

**Comment by isimarjitsingh** [comment]
Screenshot 2024-10-17 180106
please review my pr as i now changed the designing as:-
- add hover effect
- add add transitions

**Comment by isimarjitsingh** [comment]
Kindly merge it and if there is any issue, kindly let me know

**Comment by isimarjitsingh** [comment]
Screenshot 2024-10-17 214535
Kindly merge it and if there is any issue, kindly let me know

**Pull request merged**
