### PR TITLE
Alignment issue of footer section( In About Us page)

### PR DESCRIPTION
**Pull request by komalnalage**
#828 
## Related Issue#
None

## Description
The alignment of footer section in about page is done and added few hover effects as well.

## Type of PR

- [x] Bug fix
- [X ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by komalnalage** [comment]
Hi @sampadatiwari30 can you add gssoc-ext and hactoberfest-accepted tags? 
And accept my pull request of the issue that was assigned to me.

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by komalnalage** [comment]
Hi @sampadatiwari30 Can you add the labels?

**Comment by sampadatiwari30** [comment]
> Hi @sampadatiwari30 Can you add the labels?

yes

**Comment by rajdeepchakraborty-rc** [comment]
@sampadatiwari30 Please assign this PR to the Contributor and add the necessary labels along with **level** which is missing on the issue:

image

Please add the labels as the Contributor is facing issues and the points are not reflecting towards the leaderboard since the labels are not added and the PR is not assigned to the Contributor.

Have a nice day ahead!

**Pull request merged**
