### PR TITLE
Reset Password Working with help of JS

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2832 

# 👨‍💻 Description

## What does this PR do?

The reset password was not working, but its been modified with help of html, css and javascript, 

here's the output video of it, please review it.

https://github.com/user-attachments/assets/b3f3cc9b-690f-4954-b685-82a065a09040

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request.

**Comment by sampadatiwari30** [comment]
@pinakviramgama blog.html solve this conflict, and change the background.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 the background is updated as below, please check if everything is up to date and please merge this pull request.

image

**Comment by deepeshmlgupta** [comment]
@ayush-that review this PR

**Comment by ayush-that** [comment]
Pointless PR.

**Pull request closed without merging**
