### PR TITLE
Fixed the allignment of list (Quiz Links & Resources) in footer of QUIZ PAGE

### PR DESCRIPTION
**Pull request by anubhavvsharma**
#1618 

## Related Issue
The allignment of list in the footer section of Quiz page was messed.

## Description
I have added the required CSS in (quiz.html) so that the list looks properly alligned.

## Type of PR
- [X] Bug fix

## Screenshots / videos (if applicable)
BEFORE:
Screenshot (385)
AFTER:
Screenshot (384)

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by anubhavvsharma** [comment]
Hey @Sampadatiwari Do i need to raise issue everytime or just keep contributing, Will you add badges to it?

**Comment by anubhavvsharma** [comment]
And can you also please assign this one as it is displaying No assignees. @Sampadatiwari

**Comment by Sampadatiwari** [comment]
@anubhavvsharma you have to create issue. And you can also contribute, in other's issue.

**Comment by anubhavvsharma** [comment]
okay, got it. thankyou

**Pull request merged**
