### PR TITLE
Fixed: Dark/Light Mode Toggle Functionality

### PR DESCRIPTION
**Pull request by shivisingh25**
Related Issue
fixed: issue#1997 is related to Dark/Light Mode.

Description
In this update, I addressed the issue with the Dark/Light Mode, which was not functioning as expected. I implemented a few code modifications to resolve the problem, ensuring smooth transitions between modes. Please find attached the screenshots illustrating the changes post-implementation.

Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

 Screenshots / videos (if applicable)
image
image

Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by shivisingh25** [comment]
@ayush-that Please review it and label with 'gssoc-extd' and 'hactoberfest-accepted'

**Comment by shivisingh25** [comment]
@Sampadatiwari Here it is.My apology,I forgot to tag you here.

**Comment by deepeshmlgupta** [comment]
@shivisingh25 solve conflicts in index.html

**Comment by shivisingh25** [comment]
@deepeshmlgupta Done

**Pull request merged**
