### PR TITLE
Events Page Added Succesfully

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2785 

# 👨‍💻 Description

## What does this PR do?

image

1) we can add events 
2) by adding dates day of the event will be displayed automatically
3) events can be deleted
4) this page is quite imp for website like finveda

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please add this request i have resolved the issue number #2785

**Comment by pinakviramgama** [comment]
Dear sir @deepeshmlgupta , my 5 pull request are only pending since tomorrow, if there's any kind of error or issue, please assist me so i will do it, please accept my request as only my pull requests are been not accepted since one day.

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by pinakviramgama** [comment]
Thanks mam @sampadatiwari30 for accepting this request

**Pull request merged**
