### PR TITLE
fix the responsivness of quiz + fix the navbar of quiz

### PR DESCRIPTION
**Pull request by adityalaxkar123**
now quiz section is responsive for all device 

Screenshot (1046)

Screenshot (1045)

resolve the issue of navbar 

before
Screenshot (1043)

after
Screenshot (1044)

my issue no. is #1806

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@adityalaxkar123 quiz.html solve this conflict.

**Comment by adityalaxkar123** [comment]
conflict resolved and one suggestion is that you merge the pr before see that the branch has conflicts or not because i see in this project that there are many merge conflicts that are not resolved and you merged this , so that it create a negative impact on the website

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by adityalaxkar123** [comment]
Why don't give the level for the issue as you told

**Comment by adityalaxkar123** [comment]
Please give me the level for issue and close the issue it will affect my score

**Pull request merged**
