### PR TITLE
Timer Added to the quiz

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3116

# 👨‍💻 Description

## What does this PR do?

Timer  is added to the quiz so that quiz can look realistic in this quiz.html.

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @MastanSayyad , please merge this PR.

**Comment by MastanSayyad** [comment]
@Sampadatiwari @sampadatiwari30 @deepeshmlgupta

**Comment by deepeshmlgupta** [comment]
@pinakviramgama try to reclone it and then do the respective changes in that 
then you will not get these other pages added

**Comment by deepeshmlgupta** [comment]
correct this PR also

**Pull request closed without merging**
