### PR TITLE
Terms and service page modified

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2694 

# 👨‍💻 Description

Dear @sampadatiwari30 , i have resolve issue number #2694 , please review my code and please merge this pull request.

image

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@pinakviramgama index.html solve this conflict

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , i have resolved conflicts, please merge this pull reuest.

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please accept this pull  request as i have resolved issue number #2694

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this pull request as conflicts are resolved.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , please merge this pull request as conflicts are resolved

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 please accept this pull request

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta please merge this pull request

**Comment by deepeshmlgupta** [comment]
solve conflicts in index.html

Also share your output also

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , i have resolved conflicts in index.html 

here's the contribution from my side
please accept this pull request

image

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
conflicts are still there

image

**Pull request closed without merging**
