### PR TITLE
Fixed text alignment & text box size issue ! #1122

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello PR,
Fixed issue number - #1122 

Issue Fixed -

Screenshot 2024-10-14 130853

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30

**Comment by deepeshmlgupta** [comment]
solve the conficts

**Comment by Subhajit-2023-44** [comment]
> solve the conficts

@deepeshmlgupta Conflicts ? sorry I didn't find any conflicts

& why you direct closed my PR ??

**Comment by Subhajit-2023-44** [comment]
@sampadatiwari30 ??

**Comment by deepeshmlgupta** [comment]
> > solve the conficts
> 
> @deepeshmlgupta Conflicts ? sorry I didn't find any conflicts
> 
> & why you direct closed my PR ??

Sorry for the inconvenience caused by incorrect comments due to a technical issue. The issue has now been resolved. Happy contributing!

**Pull request merged**
