### PR TITLE
Contributors page fixed

### PR DESCRIPTION
**Pull request by Son7c**
# 🛠️ Fixes Issue
Fixes: #<issue_number>

# 👨‍💻 Description
Contributors section fixed with smoother animation
## What does this PR do?

- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/c3bab9fe-a530-4a71-98c9-82be1ed78c1c

# ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Son7c** [comment]
@Sampadatiwari Please review my PR

**Comment by Son7c** [comment]
@deepeshmlgupta Please review this

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by Son7c** [comment]
@sampadatiwari30 Please label it level 2 the next button was not working, i had to fix that

**Comment by Son7c** [comment]
Before

https://github.com/user-attachments/assets/9bc72423-c63c-498e-bcf7-158ec9f8b173


After

Uploading Screen Recording 2024-10-29 220004.mp4…

**Pull request merged**
