### PR TITLE
Home page fixed

### PR DESCRIPTION
**Pull request by Son7c**
# 🛠️ Fixes Issue
Fixes: #<issue_number>

# 👨‍💻 Description
Home page layout fixed

## What does this PR do?

- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/ca218fa5-66e2-466c-837f-ac9b577b9a4c

# ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Son7c** [comment]
@Sampadatiwari Please review my PR

**Comment by deepeshmlgupta** [comment]
@Son7c share your work

**Comment by Son7c** [comment]
@deepeshmlgupta I already uploaded.. i guess theres a issue

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by Son7c** [comment]
Before
https://github.com/user-attachments/assets/5a4f65dd-a9a5-458e-8eb1-4ebf566044d9

**Comment by Son7c** [comment]
@deepeshmlgupta Please mention the appropriate levels.

**Pull request merged**
