### PR TITLE
logo added

### LINKED ISSUE #981: Title: Design a logo
### Is your feature request related to a problem? Please describe.

in navbar there is no logo 

### Describe the solution you'd like.

i want to add the logo

### Describe alternatives you've considered.

N/A

### Add any other context or screenshots about the feature request here.

image
it will look like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

### PR DESCRIPTION
**Pull request by garimabhayanaa**
added logo for the website along with its tagline.

fixes #981

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@garimabhayanaa share your output.

**Comment by garimabhayanaa** [comment]
this is the logo that i have added to the repository and can be used as required.
logo

**Comment by sampadatiwari30** [comment]
@garimabhayanaa you will make it more better.

**Comment by garimabhayanaa** [comment]
okay. I will share an updated design before making another pull request.

**Comment by sampadatiwari30** [comment]
@garimabhayanaa share screenshot.

**Comment by garimabhayanaa** [comment]
Logo

**Comment by deepeshmlgupta** [comment]
> Logo

@garimabhayanaa this one looks better so update your pr and attach this png 
and once its been updated kindly tag me in this PR

**Comment by sampadatiwari30** [comment]
@garimabhayanaa this issue is resolved.

**Pull request closed without merging**
