### PR TITLE
Add a new contributors page done ! #1547

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #1547 
Add Contributors page done..

Github allows only 60 requests an hour to test and I ran out of them so I am not able to send a video/SS of it .  I'll try running the code and sending a vid an hour later after merge..

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [ ] Other (specify): _______________
## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@Sampadatiwari

**Comment by Sampadatiwari** [comment]
@Subhajit-2023-44 share your output in the form of video.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 share your output in the form of video.

There is some problem because this page is not showing contributors after about 1 hour.  I am making new PR, please wait..

**Comment by Subhajit-2023-44** [comment]
@Sampadatiwari done

**Pull request closed without merging**
