### PR TITLE
The page becomes responsive for about.html 

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2681 

# 👨‍💻 Description

The page becomes responsive for about.html and text does not go out of bound for a div

here are some screenshots which shows the responsiveness of website

image

image

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , i have resolved issue number #2681 .please approve my code and merge this pull request.

**Comment by sampadatiwari30** [comment]
@pinakviramgama index.html solve this conflict.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , i have resolved conflicts in index.html, please review my code and please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please accept this pull request as i have resolved issue number #2681

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , i have resolved the conflicts, please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , i have resolved the conflicts, please merge this pull request

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta please merge this pull request

**Review by deepeshmlgupta — APPROVED** [review]

**Pull request merged**
