### PR TITLE
Linkedin Icon added in social media icons in every page

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #3055 

# 👨‍💻 Description

## What does this PR do?

The linkedin icon in social media section was not present, but now it's added in every file.

here's the output of it.

image

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR.

**Comment by sampadatiwari30** [comment]
@pinakviramgama blog.html solve this conflict.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , conflict is resolved, please merge this PR.

**Comment by pinakviramgama** [comment]
Dear @sampadatiwari30 , please merge this PR

**Comment by pinakviramgama** [comment]
Dear @deepeshmlgupta , please merge this PR

**Comment by deepeshmlgupta** [comment]
@pinakviramgama firstly you have to remove the unnecessary files that are not needed for modification for this PR then only this PR will merge

**Comment by pinakviramgama** [comment]
Sorry sir  @deepeshmlgupta  for that blank spaces , it's by mistake

**Comment by sampadatiwari30** [comment]
@pinakviramgama blog.html
maps.html solve this conflict.

**Pull request closed without merging**
