### PR TITLE
Added new icons in the contact details

### PR DESCRIPTION
**Pull request by SadafKausar2025**
before there is no icons

Screenshot (1740)

after adding icons

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
Screenshot (1752)

**Comment by SadafKausar2025** [comment]
hi @ayush-that 

I have allign the icons properly 

can you please merge this PR?

**Comment by ayush-that** [comment]
@SadafKausar2025 
Remove conflicts.

**Comment by SadafKausar2025** [comment]
Hi , @ayush-that
@ can you please reopen the PR so that I can resolve conflicts.

**Pull request closed without merging**
