### PR TITLE
Fixed the error

### PR DESCRIPTION
**Pull request by YadlaMani**
Now it's showing underline for all pages

### CODE REVIEW

**Comment by YadlaMani** [comment]
closes #103

**Comment by YadlaMani** [comment]
@ayush-that review this once and if possible give it level 2

**Comment by ayush-that** [comment]
image
The line should be the same distance as the line that appears while hovering. 
Implement on blog article pages too.

**Comment by YadlaMani** [comment]
@ayush-that will do that and keep the pull request again

**Pull request closed without merging**
