### PR TITLE
Update blog.html by making the footer same as if present in all website

### PR DESCRIPTION
**Pull request by LavkushSolanki**
# 🛠️ Fixes Issue
Fixes: #2874 

# 👨‍💻 Description

## What does this PR do?

Made the footer as it is like it was present in other pages.

# 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots/GIFs (if any)
Screenshot (428)

# ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by LavkushSolanki** [comment]
Add my pr

**Comment by Priyanshi0112** [comment]
@LavkushSolanki 
My issue is different from yours why have you mentioned my issue ??

**Comment by LavkushSolanki** [comment]
@Priyanshi0112  footer was not correct in blog page.That's what I have corrected.

**Comment by deepeshmlgupta** [comment]
solve conflicts in blog.html

**Pull request closed without merging**
