### PR TITLE
#532 issue resolved:-quiz description box added. 

### PR DESCRIPTION
**Pull request by Vanshikachhikara**
This tells the user about the no. of questions and marks per question in the quiz.

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
Add ss to what you have solved, with before and after!

**Comment by Agarwalvidu** [comment]
#532

**Comment by Vanshikachhikara** [comment]
Okay will do

**Comment by Vanshikachhikara** [comment]
# Before:
Screenshot 2024-07-18 211916
#After : 
Screenshot 2024-07-18 211955

###description of changes:-
-added a new box which tell the user about the quiz that they are going to attempt
-it tells the number of questions and marks for each question

**Comment by Agarwalvidu** [comment]
Please correct the alignment of this!
It is not looking user friendly!

**Comment by Vanshikachhikara** [comment]
corrected the alignment of the box 
before:-
Screenshot 2024-07-18 211916
after:-
Screenshot 2024-07-18 232235

**Pull request merged**
