### PR TITLE
✨issue #1166 solved , forms have been improved✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
## Related Issue
the local storage on the form is working.

## Type of PR
- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X]  I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
@ayush-that im not able to add any video or photo right now its glitched , but its working .
if u can review this PR , i can work on the next issue i had created.

**Comment by T-Rahul-prabhu-38** [comment]
@ayush-that can you please review this PR , i have one more to make.

**Comment by deepeshmlgupta** [comment]
solve conflicts and also add a video of your work

**Comment by T-Rahul-prabhu-38** [comment]
kk

**Pull request closed without merging**
