### PR TITLE
Added search bar for jobs functionality for the issue #1262

### PR DESCRIPTION
**Pull request by DivyaJyothi9**
created a pull request for issue#1262 

## Description
Screenshot (342)

Screenshot (343)

Screenshot (344)

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by DivyaJyothi9** [comment]
@sampadatiwari30 ma'am, have created a PR for issue #1262  and added the screeenshots.
Kindly add the labels and assignee while merging.
Thank you!!

**Comment by Sampadatiwari** [comment]
@DivyaJyothi9 contact.html solve this conflict.

**Comment by DivyaJyothi9** [comment]
@sampadatiwari30 ma'am, while assigning this was level 3..could u kindly verify it #1262

**Comment by DivyaJyothi9** [comment]
@sampadatiwari30 ma'am u haven't assigned me while merging ,,plz ma'am kindly do it!!
and also level was labelled to be 2 but while assigning it was level 3..plz kindly verify it!!

**Pull request merged**
