### PR TITLE
Saving For Future Blog added

### LINKED ISSUE #794: Title: Saving for the Future Blog
### Is your feature request related to a problem? Please describe.

I want to add Blog about this Saving for the Future.

### Describe the solution you'd like.

NA

### Describe alternatives you've considered.

NA

### Add any other context or screenshots about the feature request here.

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue
- [X] I have attached the Screenshort regarding my issue

### PR DESCRIPTION
**Pull request by zalabhavy**
Fixes #794 

Added Blog Saving for Future.

image

image

### CODE REVIEW

**Comment by zalabhavy** [comment]
@Agarwalvidu @deepeshmlgupta Check this PR and Merge !

Thank You  !

**Comment by zalabhavy** [comment]
@deepeshmlgupta @Agarwalvidu Please check it and merge !

Thank You !

**Comment by Agarwalvidu** [comment]
Please resolve conflicts

**Comment by zalabhavy** [comment]
@Agarwalvidu fixed

**Pull request merged**
