### PR TITLE
Button allinged in center issue #1278

### PR DESCRIPTION
**Pull request by PDGamerSG**
## Related Issue
Button allinged in center issue #1278

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by sampadatiwari30** [comment]
@PDGamerSG assets/css/style.css solve this conflict

**Comment by PDGamerSG** [comment]
> @PDGamerSG assets/css/style.css solve this conflict

Done Mam

**Comment by PDGamerSG** [comment]
> @PDGamerSG assets/css/style.css solve this conflict

Mam pls check the pr and waiting for response

**Comment by PDGamerSG** [comment]
> @PDGamerSG assets/css/style.css solve this conflict

Mam pls check the pr and waiting for response

**Pull request merged**
