### PR TITLE
ADDED DARK MODE

### PR DESCRIPTION
**Pull request by HS202022**
ISSUE #1033
## Description
ADDED DARK MODE 

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Uploading Untitled video - Made with Clipchamp.mp4…

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by deepeshmlgupta** [comment]
@HS202022 do add a video of your work

**Comment by HS202022** [comment]
https://github.com/user-attachments/assets/1cf58503-3c53-4b5f-a9ec-f67ced676c4f

**Comment by HS202022** [comment]
> @HS202022 do add a video of your work

I already did but it didn't upload

**Comment by HS202022** [comment]
@deepeshmlgupta please add level 2 thanks

**Comment by deepeshmlgupta** [comment]
Sove the conflict

**Comment by HS202022** [comment]
@deepeshmlgupta did it please mark the level

**Pull request closed without merging**
