### PR TITLE
Corrected navbar Misalignment 

### PR DESCRIPTION
**Pull request by Priyanshi0112**
# 🛠️ Fixes Issue
Fixes: #2607 

# 👨‍💻 Description
corrected navbar misalignment issue on tool page

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)

# 📷 Screenshots/GIFs (if any)

image

# ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have made this change from my own.
- [ ] I have taken help from some online resources.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have added documentation to explain my changes.

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Sampadatiwari** [comment]
@Priyanshi0112 tools/sip.html solve this conflict.

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
solve conflicts in tools/sip.html

**Comment by Priyanshi0112** [comment]
> solve conflicts in tools/sip.html

Done

**Comment by sampadatiwari30** [comment]
@Priyanshi0112 share your final output.

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by Hemu21** [comment]
@MastanSayyad

**Comment by MastanSayyad** [comment]
@sampadatiwari30 @deepeshmlgupta remove levels

**Pull request merged**
