### PR TITLE
Welcome Page Modified with beautiful CSS

### PR DESCRIPTION
**Pull request by pinakviramgama**
# 🛠️ Fixes Issue
Fixes: #2833 

# 👨‍💻 Description

## What does this PR do?

The welcome page of the website was very untidy 
It is modified with the help of css and html

BEFORE : 
image

NOW : 
https://github.com/user-attachments/assets/5d7145b8-3dde-4c32-9163-d41a6fcc3249

### CODE REVIEW

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , please merge this pull request.

**Comment by pinakviramgama** [comment]
Dear @Sampadatiwari , the conflicts are resolved , please merge this pull request.

**Comment by deepeshmlgupta** [comment]
@ayush-that review this PR

**Comment by ayush-that** [comment]
Unnecessary PR.

**Pull request closed without merging**
