### PR TITLE
Github actions for more connectivity!

### LINKED ISSUE #1711: Github actions for more connectivity!
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ayush-that 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

### PR DESCRIPTION
**Pull request by smog-root**
Closes #1711 

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ayush-that 

_**Note**_: Add all the labels and assign me to this PR !!

### CODE REVIEW

**Review by Sampadatiwari — APPROVED** [review]

**Comment by smog-root** [comment]
**Proof**:

**Issue open and close:**

Screenshot 2024-10-21 152058
<br>

**PR raise and  merged:**
Screenshot 2024-10-21 160211

**Comment by Sampadatiwari** [comment]
@smog-root what you want to say ?

**Comment by smog-root** [comment]
> @smog-root what you want to say ?

Nothing. just sharing that it's working!! If any problem occurs you can mention me!!

**Review by MastanSayyad — COMMENTED** [review]
Hi as this PR has all workflows and got level 2 too so I'll be considering last PR #1596 as part of this and that PR will have no labels as per the guidlines

image

@deepeshmlgupta @Sampadatiwari

**Pull request merged**
