### PR TITLE
Enhanced the navbar and footer section of the website 

### PR DESCRIPTION
**Pull request by T-Fathima**
## Description
This pull request adds styling improvements to the footer section and navbar updating the padding, and applying a consistent black background with rounded corners and subtle shadows to enhance the overall UI/UX. These changes help reduce excess space and improve the layout's visual appeal.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/f94c8e3d-cdd8-4130-a3d7-16b192ab376f

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
These changes were made to ensure the page's visual hierarchy and reduce the excessive vertical spacing in smaller screen sizes, providing a better user experience for responsive designs.

@ayush-that Please review the code and merge it under gssoc-ext'24 and hacktoberfest labels.

### CODE REVIEW

**Comment by Codewithmeowmeow** [comment]
@sampadatiwari30  please assign labels and level.

**Comment by T-Fathima** [comment]
@sampadatiwari30 Thank for merging the code.
**Can u please assign labels** 
gssoc-ext'24 and hacktoberfest along with levels.

**Comment by sampadatiwari30** [comment]
@T-Fathima @Codewithmeowmeow i already assigned labels.

**Comment by T-Fathima** [comment]
image
image
Labels have not been added when merged. (Screenshots attached)
Could u please assign them again here.

**Pull request merged**
