### PR TITLE
The nescessary icons for Home has added

### PR DESCRIPTION
**Pull request by RitikaMaha**
Icon symbols #1645

## Description
The issue I raised was for changing icons for home, tools, quiz,etc. and I have done the needful changes respectively. @ayush-that @sanjay-kv @https://github.com/SampadatiwariI have made the changes and also uploaded ss. Please review the top icons that I have made and the pictures below. I request you to the do merge it into the main branch please

##Checklist:
 
I have performed a self-review of my code

- [x]  I have read and followed the Contribution Guidelines.

- [x]  I have tested the changes thoroughly before submitting this pull request.

- [x]  I have provided relevant issue numbers, screenshots, and videos after making the changes.

- [x]  I have commented my code, particularly in hard-to-understand areas.

## Screenshots / videos changes made
Screenshot 2024-10-20 195943

Original one 
Screenshot 2024-10-20 123214

### CODE REVIEW

**Comment by Sampadatiwari** [comment]
@RitikaMaha index.html solve this conflict.

**Comment by RitikaMaha** [comment]
> @RitikaMaha index.html solve this conflict.

Everything is resolved and also checked

**Review by RitikaMaha — COMMENTED** [review]
The changes in index.html have been made again

**Comment by RitikaMaha** [comment]
@sampadatiwari30 I have made again made changes in index.html

**Review by sampadatiwari30 — APPROVED** [review]

**Comment by RitikaMaha** [comment]
@Sampadatiwari can you pl. assign the labels of gssoc extended24 and also levels. It will be easy to track my record. Thanks for your support

**Review by sampadatiwari30 — APPROVED** [review]

**Pull request merged**
