### PR TITLE
TEXT now visible #1441

### PR DESCRIPTION
**Pull request by Amankr200**
#1441  

## Description
TEXT now visible

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
 
## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/7d749b17-354f-408d-8254-6977bc3e95b6

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Amankr200** [comment]
unmerged commits. why

**Comment by sampadatiwari30** [comment]
@Amankr200 another contributor has already completed this work.

**Comment by Amankr200** [comment]
I’ve put in a lot of hard work and effort into the length code changes, and it now feels like my effort has been wasted.

**Comment by sampadatiwari30** [comment]
@Amankr200 sorry for this, make sure next time your issue is not match from others.

**Pull request closed without merging**
