### PR TITLE
Added Theme Switching Button

### PR DESCRIPTION
**Pull request by TerminatorSS24**
Hey @ayush-that, I have added the **_theme switch button_** which will be applied on every page of your great website with just one click of the user.

Screenshot 2024-05-14 210223

Screenshot 2024-05-14 210202

Screenshot 2024-05-14 210148

Screenshot 2024-05-14 210135

Screenshot 2024-05-14 210124

Screenshot 2024-05-14 210058

Hope you will merge it with your repo. Please review it and give some comments about it.✌🏻

### CODE REVIEW

**Comment by ayush-that** [comment]
image
image

Not implemented correctly.

**Comment by TerminatorSS24** [comment]
ok, what things I should have to change?

**Comment by ayush-that** [comment]
> ok, what things I should have to change? @ayush-that

I might want to skip adding dark mode. This website uses Tradingview widgets. Take a look at how they implement dark mode in their widgets. https://in.tradingview.com/widget/

Also for the dark theme, a dark blue-ish dark would be preferred. Similar to https://tailwindcss.com/ website.

**Comment by TerminatorSS24** [comment]
OK, I'll try my best this time to solve this issue.

**Pull request closed without merging**
