### PR TITLE
Fixing footer on all pages

### PR DESCRIPTION
**Pull request by dipak2005**
# 🛠️ Fixes Issue
Fixes: #3177 
Closes: #3177 

# 👨‍💻 Description

 i'm improve the all footer's alignment and background colors and so on.

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# 📷 Screenshots : 
before changes : 
Screenshot 2024-11-10 053026
Screenshot 2024-11-10 053515
Screenshot 2024-11-10 053806
Screenshot 2024-11-10 053756
Screenshot 2024-11-10 053748
Screenshot 2024-11-10 053727
Screenshot 2024-11-10 053718

after changes :
 
Screenshot 2024-11-10 061543
Screenshot 2024-11-10 061532
Screenshot 2024-11-10 061523
Screenshot 2024-11-10 061511
Screenshot 2024-11-10 061501
Screenshot 2024-11-10 061451
Screenshot 2024-11-10 061420
Screenshot 2024-11-10 061406

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by dipak2005** [comment]
@deepeshmlgupta , @sampadatiwari30 
Kindly consider this pr.

**Comment by deepeshmlgupta** [comment]
solve conflicts in 
contributors.html
faq.html

**Comment by dipak2005** [comment]
@deepeshmlgupta i resolve it , check this pr.

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by deepeshmlgupta** [comment]
image
@dipak2005 solve it

**Comment by dipak2005** [comment]
Screenshot 2024-11-10 143551
done sir @deepeshmlgupta

**Pull request merged**
