### PR TITLE
Create a Responsive Project Statistics section done !

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Create a Responsive Project Statistics section done !

I have created a new Project Statistics section. This Project Statistics section  is fully responsive, Now its values ​​are dynamically updating, also I made it according to the theme..

Before -

Screenshot 2024-11-05 015819

Now -

Screenshot 2024-11-05 020017
image
Screenshot 2024-11-05 020249

# 📄 Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

# ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have made this change from my own.
- [x] I have taken help from some online resources.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have added documentation to explain my changes.

## Mandatory Tasks

- [x] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

# 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC program.
- [x] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta

**Review by deepeshmlgupta — APPROVED** [review]

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta sir can you give me level 3 for this if possible 🙏🏻.. because I have created a new Project Statistics section. This Project Statistics section is fully responsive, Now its values ​​are dynamically updating, also I made it according to the theme..

I will be very grateful if you can give me level 3 for this.. Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta sir can you give me level 3 for this if possible 🙏🏻.. because I have created a new Project Statistics section. This Project Statistics section is fully responsive, Now its values ​​are dynamically updating, also I made it according to the theme..

I will be very grateful if you can give me level 3 for this.. Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@deepeshmlgupta sir

**Pull request merged**
